In [48]:
import numpy as np

# Soal 1

In [19]:
np.arange(10)

#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr = np.arange(10)
np.array([list(arr[:5]),list(arr[5:])])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
#reshape merubah struktur dari array numpy menjadi (row, column) yang diinginkan. 
#Jika kita menulis -1 berarti numpy array akan secara otomatis menyesuaikan jumlah row atau column nya

np.arange(10).reshape(-1,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Soal 2

In [28]:
arr = np.arange(4,13).reshape(3,3)
arr

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [37]:
#Indexing menggunakan [row, column] bisa menjadi berlipat jika kita memasukkan index yang sama di dalam list row atau column
#yang diinginkan

arr[:,[1,2,0,0,1,2,1]]

array([[ 5,  6,  4,  4,  5,  6,  5],
       [ 8,  9,  7,  7,  8,  9,  8],
       [11, 12, 10, 10, 11, 12, 11]])

## Soal 3

In [38]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
#Sama seperti indexing pada saat di list, bisa menggunakan ::-1 untuk melakukan reverse baik di tingkat row ataupun column
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

## Soal 4

In [44]:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
array_of_arrays

array([array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])],
      dtype=object)

In [47]:
list_kosong = []
for ar in array_of_arrays:
    for i in ar:
        list_kosong.append(i)
np.array(list_kosong)        

# arr = np.array([i for ar in array_of_arrays for i in ar])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])