In [1]:
import numpy as np

# Soal 1

In [2]:
np.arange(10)
#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr = np.arange(10)
np.array([(arr[:5]), (arr[5:])])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Soal 2

In [4]:
arr = np.arange(4,13).reshape(3,3)
arr

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [5]:
arr[:,[1,2,0,0,1,2,1]]

array([[ 5,  6,  4,  4,  5,  6,  5],
       [ 8,  9,  7,  7,  8,  9,  8],
       [11, 12, 10, 10, 11, 12, 11]])

## Soal 3

In [6]:
arr2 = np.arange(9).reshape(3,3)
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
arr2[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

## Soal 4

In [8]:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
array_of_arrays

array([array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])],
      dtype=object)

In [9]:
arr4 = np.arange(10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
list_kosong = []
for ar in array_of_arrays:
    for i in ar:
        list_kosong.append(i)
np.array(list_kosong)        

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr5 = np.array([i for ar in array_of_arrays for i in ar])
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])